- hosts: remote
  roles:
    - common
    - docker
    - kubeadm
- hosts: registry[0]
  roles:
    - registry
- hosts: master
  roles:
    - master
    - deploy
- hosts: node
  roles:
    - node
- hosts: remote
  tasks:
    - name: Upload config file for kubelet
      template:
        src: "templates/01-pause.conf.j2"
        dest: "/etc/systemd/system/kubelet.service.d/01-pause.conf"
    - name: Enable kubelet service
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
        daemon-reload: yes
- hosts: master[0]
  tasks:
  - name: Upload approver.
    copy:
      src: files/auto_approve_csr.sh
      dest: /usr/local/bin
      mode: 0755
  - name: approve csr
    shell: /usr/local/bin/auto_approve_csr.sh
