- name: Uploading rpms
  include_tasks: rpm.yml
  vars:
    current_rpm: "{{ item }}.rpm"
  with_items: "{{ kubeadm_rpms }}"
  when: ansible_distribution == "CentOS"
- name: Install rpms
  yum:
    name: "/tmp/{{ item }}.rpm"
    state: present
  with_items: "{{ kubeadm_rpms }}"
  when: ansible_distribution == "CentOS"
- name: Installing debs
  include_tasks: deb.yml
  when: ansible_distribution == "Ubuntu"
- name: Start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
- name: Processing images
  include_tasks:  image.yml
  vars:
    current_image: "{{ item }}"
  with_items: "{{ kubeadm_images }}"
