---
- name: Disable selinux
  selinux: state=disabled
- name: turn off some services
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - firewalld
  ignore_errors: yes
- name: sysctl.
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
  ignore_errors: yes
- name: Turning off swap.
  include_tasks: noswap.yml
