---
- name: Disable selinux
  selinux: state=disabled
- name: turn off some services
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - firewalld
  ignore_errors: yes
- name: sysctl
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
  ignore_errors: yes
- name: Turning off swap.
  include_tasks: noswap.yml
