- name: Setting up the cluster
  template:
    src: "templates/cluster.init.sh.j2"
    dest: "/usr/local/bin/cluster.init.sh"
    mode: 0755
- name: kubeadm init
  shell: "/usr/local/bin/cluster.init.sh"
- name: Get home
  shell: "pwd"
  register: home_env
- name: Copy config file
  file:
    path: "{{ home_env.stdout }}/.kube"
    state: "directory"
- shell: "cp /etc/kubernetes/admin.conf {{ home_env.stdout }}/.kube/config"
- file:
    path: "{{ home_env.stdout }}/.kube/config"
    mode: "0666"
