- name: copy rpm files
  copy: 
    src: files/docker/rpm/{{ item }}  
    dest: /tmp/{{ item }}
  with_items: "{{ docker_package }}"
- name: install rpm files
  yum: 
    name: "/tmp/{{ item }}"
    state: "present"
  with_items: "{{ docker_package }}"
